options {
    directory "/var/cache/bind";

    server-id "ns1.%DOMAIN%";
    hostname "ns1.%DOMAIN%";

    dnssec-validation no;
    recursion no;

    listen-on port 53 {
        localhost;
        100.64.0.54;
    };

    listen-on-v6 port 53 {
        localhost;
        %IPv6pfx%:0::54;
    };

    allow-query {
        any;
    };

    allow-transfer {
    };

    also-notify {
    };
};

//
// Dynamic updates for DS records of delegated group zones
//

acl "ddns-allowed" {
    100.64.0.0/16;
    !100.64.0.53;
};

include "/etc/bind/nsupdate.key";

//
// Platform authoritative zone
//

zone "%DOMAIN%" {
    type primary;

    file "/var/lib/bind/zones/db.%DOMAIN%";

    dnssec-policy default;

    update-policy {
        grant nsupdate.key zonesub DS;
    };
};
