-- dnsdist configuration file, an example can be found in /usr/share/doc/dnsdist/examples/

setLocal('100.64.0.53')
addLocal('%IPv6pfx%::53')

-- control socket
-- controlSocket('127.0.0.1:5199')

-- ACL 
addACL('0.0.0.0/0')
addACL('::0/0')

-- security config
addAction(OpcodeRule(DNSOpcode.Notify), RCodeAction(DNSRCode.REFUSED))
addAction(OpcodeRule(DNSOpcode.Update), RCodeAction(DNSRCode.REFUSED))
addAction(QTypeRule(DNSQType.AXFR),     RCodeAction(DNSRCode.REFUSED))
addAction(QTypeRule(DNSQType.IXFR),     RCodeAction(DNSRCode.REFUSED))
addAction(QClassRule(DNSClass.CHAOS),   RCodeAction(DNSRCode.REFUSED))

-- disable security status polling via DNS
setSecurityPollSuffix("")

-- server selection policy
setServerPolicy(roundrobin)

-- authns
newServer({address="100.64.0.54", pool="authns", healthCheckMode='lazy', checkInterval=30}):setUp()
addAction(QTypeRule(DNSQType.DS), PoolAction("authns"))
addAction(QNameSuffixRule{"%DOMAIN%"}, PoolAction("authns"))

