source "https://rubygems.org"
gem "jekyll", "~> 4.4.1"
group :jekyll_plugins do
    gem "jekyll-relative-links"
    gem "just-the-docs"
    gem "jekyll-gfm-admonitions"
    gem "jekyll-readme-index"
    gem "jemoji"
end
