options {
    directory "/var/cache/bind";

    server-id "auth-exercise";
    hostname "auth-exercise";

    dnssec-validation no;
    recursion no;

    listen-on port 53 {
        localhost;
        100.64.0.55;
        100.64.0.56;
        100.64.0.57;
    };

    listen-on-v6 port 53 {
        localhost;
        %IPv6pfx%:0::55;
        %IPv6pfx%:0::56;
        %IPv6pfx%:0::57;
    };

    allow-query {
        any;
    };

    allow-transfer {
    };

    also-notify {
    };
};

acl "addr55" {
    100.64.0.55;
    %IPv6pfx%:0::55;
};

acl "addr56" {
    100.64.0.56;
    %IPv6pfx%:0::56;
};

acl "addr57" {
    100.64.0.57;
    %IPv6pfx%:0::57;
};

//
// Main exercise authoritative endpoint
//

view "exercise-main" {
    match-destinations {
        addr55;
    };

    recursion no;

    zone "internal" {
        type primary;
        file "/var/lib/bind/zones/db.internal";
    };
};

//
// Special exercise target #1
//

view "exercise-badnsname" {
    match-destinations {
        addr56;
    };

    recursion no;

    zone "badnsname.internal" {
        type primary;
        file "/var/lib/bind/zones/db.badnsname.internal";
    };
};

//
// Special exercise target #2
//

view "exercise-evilnsip" {
    match-destinations {
        addr57;
    };

    recursion no;

    zone "evilnsip.internal" {
        type primary;
        file "/var/lib/bind/zones/db.evilnsip.internal";
    };
};
