apiVersion: v1
kind: Service
metadata:
  name: {{ include "java.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "java.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "java.name" . }}
    release: {{ .Release.Name }}