options {
    directory "/var/cache/bind";

    server-id "auth-rpz";
    hostname "auth-rpz";

    dnssec-validation no;
    recursion no;

    listen-on port 53 {
        localhost;
        100.64.0.58;
    };

    listen-on-v6 port 53 {
        localhost;
        %IPv6pfx%:0::58;
    };

    allow-query {
        any;
    };

    allow-transfer {
        100.100.0.0/16;
        %IPv6pfx%::/32;
    };

    also-notify {
    };
};

zone "rpz" {
    type primary;
    file "/var/lib/bind/zones/db.rpz";
};
