name: Sync to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.gitignore' --exclude '.github/*' --exclude '.git/*' 
      env:
        AWS_S3_BUCKET: ${{ secrets.DESTINATION_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
