name: Sync to S3
on:
  push:
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      destination_bucket: ${{ steps.setvars.outputs.destination_bucket }}
    steps:
    - name: Set variables
      id: setvars
      run: |
        if [[ "${{ github.base_ref }}" == "main" || "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "destination_bucket=${{ secrets.DESTINATION_BUCKET }}" >> "$GITHUB_OUTPUT"
        else
          echo "destination_bucket=${{ secrets.DESTINATION_BUCKET }}-${{ github.base_ref }}" >> "$GITHUB_OUTPUT"
        fi
  deploy:
    runs-on: ubuntu-latest
    needs: init
    steps:
    - name: Create bucket in S3
      uses: aitorres/aws-s3-create-bucket@v1.2.0
      with:
        bucket-name: ${{ needs.init.destination_bucket }}
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'
        acl: 'private'
    - uses: actions/checkout@v2
    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.gitignore' --exclude '.github/*' --exclude '.git/*' 
      env:
        AWS_S3_BUCKET: ${{ needs.init.destination_bucket }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'
